{"name": "test_login_001", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <scripts.test_login.TestLogin object at 0x0000023CA2331BE0>\n\n    def test_login_001(self):\n>       assert 0\nE       assert 0\n\nscripts\\test_login.py:4: AssertionError"}, "start": 1585418096354, "stop": 1585418096354, "uuid": "2d56e49f-43f1-4d7b-9362-9612f125202a", "historyId": "14ed3a6f43764b7f6f01338819c9c297", "testCaseId": "61fd03ca604429f4bd9d857ac5f51598", "fullName": "scripts.test_login.TestLogin#test_login_001", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-O35TFJO"}, {"name": "thread", "value": "3244-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_login"}]}